name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 1.1.9
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=2.15.1 <3.0.0"

dependency_overrides:
  convert: ^3.1.1
  crypto: ^3.0.2
  test_api: ^0.4.16
  vm_service: ^9.4.0
  coverage: ^1.6.1
  args: ^2.3.1

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  glob: ^2.0.1
  meta: ">=1.1.6 <2.0.0"
  gherkin: ^2.0.0
  # gherkin:
    # path: ../dart_gherkin

dev_dependencies:
  test:
  pedantic: ^1.9.2

flutter:
