name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 1.1.9
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependency_overrides:
  crypto: ^3.0.0 # flutter_driver still depends on 2.1.5 see https://github.com/flutter/flutter/issues/80293
  convert: ^3.0.0 # flutter_driver still depends on >=2.0.0 see https://github.com/flutter/flutter/issues/80293
  test_api: ^0.4.0 # flutter_test still depends on 0.2.19 see https://github.com/flutter/flutter/issues/80293
  vm_service: ^6.0.0 # flutter_test still depends on 5.5.0 see https://github.com/flutter/flutter/issues/80293
  test: ^1.17.3 # integration_test still depends on 1.16.6 see https://github.com/flutter/flutter/issues/71379
  args: ^2.0.0 # flutter_driver still depends on 1.6.0 see https://github.com/flutter/flutter/issues/80293

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  glob: ^2.0.1
  meta: ">=1.1.6 <2.0.0"
  gherkin: ^2.0.0
  # gherkin:
    # path: ../dart_gherkin

dev_dependencies:
  test:
  pedantic: ^1.9.2

flutter:
